apiVersion: apps/v1
kind: Deployment
metadata:
  name: speed
  labels:
    app: speed
spec:
  selector:
    matchLabels:
      app: speed
  replicas: 1

  template:
    metadata:
     name: speed
     labels:
      app: speed
    spec:
     containers:
      - name: speed
        image: mukesh92/speed3:${TAG}
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: speed-svc
spec:
 selector:
   app: speed
 ports:
   - protocol: "TCP"
     port: 8080
     targetPort: 8080
     nodePort: 31081
 type: NodePort
